# Site settings
title: Jacob Bowman's Super Simple Blog
author:
  name: Jacob Bowman
  email: jake.bowman1018@gmail.com
description: "A blog of likely insignificance"

# Build settings
remote_theme: jekyll/minima
skin: dark
